import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import Header from "./partials/header/index";
import Footer from "./partials/footer/index";
import {Datagrid} from "./components/datagrid"; 
import reportWebVitals from './reportWebVitals';
import {Switch, BrowserRouter, Router, Route,} from "react-router-dom";
import {AboutUs} from './content/about'
import {ById} from "./content/byId"
import {Home} from "./content/home"
import {Movies} from "./content/movies"

ReactDOM.render(
  <React.StrictMode>
    <BrowserRouter forceRefresh={true}>
      <Header/>
      <main>
          <Switch>
            <Route exact path="/about" component={AboutUs} />
            <Route path="/actors/byId/:id?" component={ById} />
            <Route path="/actors">
              <Datagrid >
                  <h1>Sakila Actors</h1>
                  <p>Loaded from the default MySql Database. Profile images are autogenerated from and archive of https://thispersondoesnotexist.com/ and randomly assigned to the actors. </p>
                  <p>This should be rewritten for more generic item handling. This will also need authorization for edits. The edits will POST back to the API, but changes are not made at this time.</p>
                  </Datagrid>
            </Route>
            <Route path="/movies" component={Movies} />
            <Route path="/" component={Home} />
          </Switch>
      </main>
      <Footer>
        <h3>disclaimer</h3>
        <p>This is not production ready.</p>
      </Footer>
    </BrowserRouter>
  </React.StrictMode>,
  document.getElementById('root')
);

// If you want to start measuring performance in your app, pass a function
// to log results (for example: reportWebVitals(console.log))
// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
reportWebVitals();
